#!/bin/bash
cat << EOF

	feat:		A new feature
	fix:		A bug fix
	perf:		A code change that improves performance
	refactor:	A code change that neither fixes a bug nor adds a feature
	chore:		updating gulp tasks etc.
	vendor:	update version for dependencies, packages.
	build:		Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)
	ci:		Changes to our CI configuration files and scripts (example scopes: Circle, BrowserStack, SauceLabs)
	docs:		Documentation only changes
	style:		Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
	test:		Adding missing tests or correcting existing tests

EOF
